### ISSUE TITLE
Tests fail locally

### ISSUE THREAD

**Issue by SPlanzer** [linz/linz-data-importer#121]
When running `./test.bash latest <linz_key> <mfe_key> <nzdf_key> <basemaps_key> ` a traceback is caught and tests hang. I suspect they hang as the dialogue will be left open in the container. 

my environment
* Docker version: '20.10.6, build 370c289'
* Project Branch" 'main'

Results of running the above command:

```
latest: Pulling from qgis/qgis
345e3491a907: Already exists 
57671312ef6f: Already exists 
5e9250ddb7d0: Already exists 
512296be1ba0: Already exists 
7a4c6e4cde3a: Already exists 
038c7e416fd4: Already exists 
69c49f8095ff: Already exists 
c24cd3df7c00: Already exists 
882215d1771b: Already exists 
aa839f821568: Already exists 
dc7d26963ebf: Already exists 
9dc3e6a25571: Already exists 
625ad6b36c53: Already exists 
3e3cf6bf518f: Already exists 
0845662b838b: Already exists 
4733a6b8f880: Already exists 
2f361221d465: Already exists 
994f1760d2cd: Already exists 
6301d2d0a430: Already exists 
fe8302f2dd6a: Already exists 
1f26982e76e4: Already exists 
e4e273980dd8: Already exists 
bd96e968adcf: Already exists 
8c886240dd7b: Pull complete 
Digest: sha256:42af44d1c273fb4ba6338fb131ea63297b03f9a1c72ee30e5b8f79e8ac018adb
Status: Downloaded newer image for qgis/qgis:latest
89d7ab91b8d1371e4c8f35b1cd680b92be53005f3528244670cb1680b3118ac6
Plugin master folder linked in /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer
Running test linz-data-importer.tests.run_tests.run_test_modules ...
Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
"<font color=\"red\">An error occurred during execution of following code:<br><tt>import pyplugin_installer</tt></font><br><pre><br>Traceback (most recent call last):<br>&nbsp; File \"/usr/lib/python3/dist-packages/qgis/utils.py\", line 335, in _startPlugin<br>&nbsp; &nbsp; plugins[packageName] = package.classFactory(iface)<br>&nbsp; File \"/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/__init__.py\", line 36, in classFactory<br>&nbsp; &nbsp; return LinzDataImporter()<br>TypeError: __init__() missing 1 required positional argument: 'iface'<br><br>During handling of the above exception, another exception occurred:<br><br>Traceback (most recent call last):<br>&nbsp; File \"<string>\", line 1, in <module><br>&nbsp; File \"/usr/lib/python3/dist-packages/qgis/utils.py\", line 355, in startPlugin<br>&nbsp; &nbsp; if not _startPlugin(packageName):<br>&nbsp; File \"/usr/lib/python3/dist-packages/qgis/utils.py\", line 340, in _startPlugin<br>&nbsp; &nbsp; showException(sys.exc_info()[0], sys.exc_info()[1], sys.exc_info()[2], msg, messagebar=True, level=Qgis.Critical)<br>TypeError: _showException() got an unexpected keyword argument 'level'<br><br></pre>Python version:<br>3.8.5 (default, Jan 27 2021, 15:41:15) <br>[GCC 9.3.0]<br><br>QGIS version:<br>3.19.0-Master 'Master', exported<br><br>Python path:<br>['/usr/share/qgis/python', '/root/.local/share/QGIS/QGIS3/profiles/default/python', '/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/share/qgis/python', '/usr/share/qgis/python/plugins', '/usr/lib/python3/dist-packages/qgis', '/usr/share/qgis/python/qgis', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/root/.local/share/QGIS/QGIS3/profiles/default/python']"

```

**Comment by l0b0** [comment]
The traceback in readable form:

```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/lib/python3/dist-packages/qgis/utils.py", line 355, in startPlugin
if not _startPlugin(packageName):
File "/usr/lib/python3/dist-packages/qgis/utils.py", line 340, in _startPlugin
showException(sys.exc_info()[0], sys.exc_info()[1], sys.exc_info()[2], msg, messagebar=True, level=Qgis.Critical)
TypeError: _showException() got an unexpected keyword argument 'level'
```

This looks like some internal issue with QGIS. Could you please try running with `release-3_16` rather than `latest`?

**Comment by SPlanzer** [comment]
trying with 3.16
```
...
e4e273980dd8: Already exists 
bd96e968adcf: Already exists 
365e066bd7b4: Pull complete 
Digest: sha256:15aaa67b00f2d5fdd4290bbf6aff5866e4a64e527acbada8a99a45dce6b5278d
Status: Downloaded newer image for qgis/qgis:release-3_16
d02f852e20d0659cebedd3e68ccdb2fd287c9d16707960e56571830756378b71
Plugin master folder linked in /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer
Running test linz-data-importer.tests.run_tests.run_test_modules ...
Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
"<font color=\"red\">An error occurred during execution of following code:<br><tt>import pyplugin_installer</tt></font><br><pre><br>Traceback (most recent call last):<br>&nbsp; File \"/usr/lib/python3/dist-packages/qgis/utils.py\", line 334, in _startPlugin<br>&nbsp; &nbsp; plugins[packageName] = package.classFactory(iface)<br>&nbsp; File \"/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/__init__.py\", line 36, in classFactory<br>&nbsp; &nbsp; return LinzDataImporter()<br>TypeError: __init__() missing 1 required positional argument: 'iface'<br><br>During handling of the above exception, another exception occurred:<br><br>Traceback (most recent call last):<br>&nbsp; File \"<string>\", line 1, in <module><br>&nbsp; File \"/usr/lib/python3/dist-packages/qgis/utils.py\", line 354, in startPlugin<br>&nbsp; &nbsp; if not _startPlugin(packageName):<br>&nbsp; File \"/usr/lib/python3/dist-packages/qgis/utils.py\", line 339, in _startPlugin<br>&nbsp; &nbsp; showException(sys.exc_info()[0], sys.exc_info()[1], sys.exc_info()[2], msg, messagebar=True, level=Qgis.Critical)<br>TypeError: _showException() got an unexpected keyword argument 'level'<br><br></pre>Python version:<br>3.8.5 (default, Jan 27 2021, 15:41:15) <br>[GCC 9.3.0]<br><br>QGIS version:<br>3.16.7-Hannover 'Hannover', exported<br><br>Python path:<br>['/usr/share/qgis/python', '/root/.local/share/QGIS/QGIS3/profiles/default/python', '/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/share/qgis/python', '/usr/share/qgis/python/plugins', '/usr/lib/python3/dist-packages/qgis', '/usr/share/qgis/python/qgis', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/root/.local/share/QGIS/QGIS3/profiles/default/python']"
```

**Comment by l0b0** [comment]
```
Traceback (most recent call last):
File \"/usr/lib/python3/dist-packages/qgis/utils.py\", line 334, in _startPlugin
plugins[packageName] = package.classFactory(iface)
File \"/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/__init__.py\", line 36, in classFactory
return LinzDataImporter()
TypeError: __init__() missing 1 required positional argument: 'iface'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File \"<string>\", line 1, in <module>
File \"/usr/lib/python3/dist-packages/qgis/utils.py\", line 354, in startPlugin
if not _startPlugin(packageName):
File \"/usr/lib/python3/dist-packages/qgis/utils.py\", line 339, in _startPlugin
showException(sys.exc_info()[0], sys.exc_info()[1], sys.exc_info()[2], msg, messagebar=True, level=Qgis.Critical)
TypeError: _showException() got an unexpected keyword argument 'level'
```

**Comment by l0b0** [comment]
Can you see what the dialogue is in in the container? I'm kinda lost for why this is failing, and I can't reproduce :/

**Comment by SPlanzer** [comment]
Sorry removed the container and started again. It worked after this

I will close for now
