### ISSUE TITLE
plugin fails with QGIS 3.4.0 (did work in 3.2) due to owslib regression

### ISSUE THREAD

**Issue by SPlanzer** [linz/linz-data-importer#42]
As per below new QGIS releases released newer python owslib versions. But with 3.4 a much older version of the python owslib was packaged. 

```
QGis.QGIS_VERSION
'2.18.16'
owslib.__version__
'0.14.0'
```

```
Qgis.QGIS_VERSION
'3.2.3-Bonn'
owslib.__version__
'0.16.0'
```

```
Qgis.QGIS_VERSION
'3.4.0-Madeira'
owslib.__version__
'0.10.3'
```

**Comment by SPlanzer** [comment]
The error is related to the xml object passed to the owslib 
```
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration. 
Traceback (most recent call last):
  File "/home/splanzer/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/linz_data_importer.py", line 429, in run
    self.loadUi()
  File "/home/splanzer/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/linz_data_importer.py", line 454, in loadUi
    load_data_err=self.loadAllServices()
  File "/home/splanzer/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/linz_data_importer.py", line 479, in loadAllServices
    service_data_instance.processServiceData()
  File "/home/splanzer/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/service_data.py", line 274, in processServiceData
    self.getServiceObj()
  File "/home/splanzer/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/service_data.py", line 288, in getServiceObj
    self.obj = WebMapTileService(url=None, xml=self.xml, version=self.version,)
  File "/usr/lib/python3/dist-packages/owslib/wmts.py", line 166, in __init__
    self._capabilities = reader.readString(xml)
  File "/usr/lib/python3/dist-packages/owslib/wmts.py", line 815, in readString
    return etree.fromstring(st)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:82934)
  File "src/lxml/parser.pxi", line 1814, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124471)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

**Comment by SPlanzer** [comment]
This is just related to the current `ubuntugis-unstable` repo version
* I have installed QGIS 3.4 (code revision 4a4b62e) into Ubuntu_18 (virtual box) from `https://qgis.org/ubuntu` and this is running owslib==0.16.0

* Interestingly when downloading and installing QGIS (code version 4a4b62ed19) for windows owslib==0.17.0

**Comment by SPlanzer** [comment]
This is an issue my end with the installation. I note [launchpad](https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable) has the correct owslib version

A standard install using "unstable" fails for me

```
splanzer@splanzer-HP-EliteBook-820-G2:~$ sudo apt-get update && sudo apt-get install qgis python-qgis qgis-plugin-grass
Hit:1 http://nz.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://nz.archive.ubuntu.com/ubuntu xenial-updates InRelease             
Get:3 http://nz.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]  
Hit:4 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu xenial InRelease     
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]     
Hit:6 https://download.virtualbox.org/virtualbox/debian xenial InRelease       
Hit:7 http://ppa.launchpad.net/jtaylor/keepass/ubuntu xenial InRelease         
Hit:8 http://apt.postgresql.org/pub/repos/apt xenial-pgdg InRelease            
Hit:9 http://ppa.launchpad.net/peek-developers/stable/ubuntu xenial InRelease  
Hit:10 https://qgis.org/ubuntugis xenial InRelease                             
Hit:11 http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu xenial InRelease
Hit:12 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease       
Hit:13 http://ppa.launchpad.net/webupd8team/sublime-text-2/ubuntu xenial InRelease
Hit:14 http://ppa.launchpad.net/webupd8team/sublime-text-3/ubuntu xenial InRelease
Fetched 214 kB in 5s (40.9 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-qgis : Depends: python-qgis-common (= 1:3.4.0+24xenial-ubuntugis) but 1:3.4.0+git20181030+21d1bdf+24xenial-ubuntugis is to be installed
 qgis : Depends: qgis-providers (= 1:3.4.0+24xenial-ubuntugis) but 1:3.4.0+git20181030+21d1bdf+24xenial-ubuntugis is to be installed
        Depends: qgis-common (= 1:3.4.0+24xenial-ubuntugis) but 1:3.4.0+git20181030+21d1bdf+24xenial-ubuntugis is to be installed
 qgis-plugin-grass : Depends: grass741 but it is not installable
E: Unable to correct problems, you have held broken packages.
``` 
To get a working install in Xenial I have had to use aptitude which removes python3-owslib 

```
The following NEW packages will be installed:
  grass-core{a} liblas-c3{a} liblas3{a} libqgisgrass7-3.4.0{a} 
  python-qgis{b} qgis{b} qgis-plugin-grass{b} qgis-plugin-grass-common{a} 
  qgis-provider-grass{a} 
The following packages will be REMOVED:
  libfcgi0ldbl{u} libjs-jquery-ui{u} libjs-leaflet{u} liblwgeom-2.5-0{u} 
  libqca-qt5-2-plugins{u} libqgis-customwidgets{u} libqgis-native3.4.0{u} 
  libqt5scintilla2-l10n{u} libqt5serialport5{u} libqwt-qt5-6{u} 
  libspatialindex4v5{u} libzip4{u} python-matplotlib-data{u} 
  python-qgis-common{u} python3-cycler{u} python3-gdal{u} 
  python3-matplotlib{u} python3-numpy{u} python3-tk{u} qgis-common{u} 
  qgis-providers{u} qgis-providers-common{u} 
0 packages upgraded, 9 newly installed, 22 to remove and 89 not upgraded.
Need to get 8,818 kB/28.9 MB of archives. After unpacking 167 MB will be freed.
The following packages have unmet dependencies:
 libqgis-analysis3.4.0 : Depends: libspatialindex4v5 (>= 1.8.5) but it is not going to be installed.
 libqgis-app3.4.0 : Depends: libqgis-native3.4.0 but it is not going to be installed.
                    Depends: libqwt-qt5-6 (>= 6.1.2) but it is not going to be installed.
 libqgis-server3.4.0 : Depends: libfcgi0ldbl but it is not going to be installed.
 qgis-plugin-grass : Depends: grass741 which is a virtual package and is not provided by any available package.

 qgis : Depends: qgis-providers (= 1:3.4.0+24xenial-ubuntugis) but it is not going to be installed.
        Depends: qgis-common (= 1:3.4.0+24xenial-ubuntugis) but it is not going to be installed.
 python-qgis : Depends: python-qgis-common (= 1:3.4.0+24xenial-ubuntugis) but it is not going to be installed.
 libqt5scintilla2-12v5 : Depends: libqt5scintilla2-l10n (>= 2.9.1+dfsg) but it is not going to be installed.
 liblwgeom-dev : Depends: liblwgeom-2.5-0 (= 2.5.0+dfsg-2.pgdg16.04+1) but it is not going to be installed.
 python3-pyproj : Depends: python3-numpy (>= 1:1.8.0) but it is not going to be installed.
                  Depends: python3-numpy-abi9 which is a virtual package, provided by:
                            - python3-numpy, but it is not going to be installed.
 libqgis-core3.4.0 : Depends: libqt5serialport5 (>= 5.1.0) but it is not going to be installed.
                     Depends: libspatialindex4v5 (>= 1.8.5) but it is not going to be installed.
                     Depends: libzip4 (>= 0.11.2) but it is not going to be installed.
 libqgis-gui3.4.0 : Depends: libqgis-native3.4.0 but it is not going to be installed.
                    Depends: libqwt-qt5-6 (>= 6.1.2) but it is not going to be installed.
The following actions will resolve these dependencies:

      Remove the following packages:                       
1)      liblwgeom-dev                                      
2)      libqgis-analysis3.4.0                              
3)      libqgis-app3.4.0                                   
4)      libqgis-core3.4.0                                  
5)      libqgis-gui3.4.0                                   
6)      libqgis-server3.4.0                                
7)      libqgispython3.4.0                                 
8)      libqt5scintilla2-12v5                              
9)      python3-owslib                                     
10)     python3-pyproj                                     
11)     python3-pyqt5.qsci                                 

      Keep the following packages at their current version:
12)     libqgisgrass7-3.4.0 [Not Installed]                
13)     python-qgis [Not Installed]                        
14)     qgis [Not Installed]                               
15)     qgis-plugin-grass [Not Installed]                  
16)     qgis-provider-grass [Not Installed]                

      Leave the following dependencies unresolved:         
17)     libqca-qt5-2 recommends libqca-qt5-2-plugins       
18)     qgis recommends qgis-plugin-grass      
```

**Comment by SPlanzer** [comment]
I must resolve my hacky QGIS installation. This project is on hold while LINZ users use the QGIS2 version and provide feedback. 

Providing positive feedback, The ported QGIS3 version will be finalised. (Unit tests to port still)

**Comment by SPlanzer** [comment]
I have this working against 3.4 where I have upgraded the owslib myself. My QGIS3.4 install is hacky. I wIll live with this for now for dev. Testing to be conducted against ubuntu 18 with QGIS 3.4 virtual machine and travis with QGIS3 instance.
