### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by billgeo** [linz/linz-data-importer#63]
https://travis-ci.com/github/linz/linz-data-importer/builds/182171464

**Comment by strk** [comment]
First error is:
> test_importDataset_wfs (test_ldi_plugin.UnitLevel) ... Warning: QXcbConnection: XCB error: 8 (BadMatch), sequence: 1191, resource id: 2097167, major code: 42 (SetInputFocus), minor code: 0

Sounds related to X authorization

**Comment by strk** [comment]
It looks like a different error than the X authorization (which is just a warning):
```
Traceback (most recent call last):

  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/linz_data_importer.py", line 433, in run

    self.loadUi()

  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/linz_data_importer.py", line 461, in loadUi

    load_data_err=self.loadAllServices()

  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/linz_data_importer.py", line 497, in loadAllServices

    service_data_instance.processServiceData()

  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/service_data.py", line 320, in processServiceData

    self.getServiceData()

  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/service_data.py", line 297, in getServiceData

    self.getServiceXml()

  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/service_data.py", line 359, in getServiceXml

    self.api_key_int.getApiKey(self.domain),

  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer/service_data.py", line 75, in getApiKey

    return self.api_keys[domain]

KeyError: 'data.linz.govt.nz'
```

**Comment by SPlanzer** [comment]
I am guessing this is as the LDS API key the CI is using may have been revoked. This will be stored as a Travis secret and will need to be reallocated and re-encrypted for Travis

**Comment by billgeo** [comment]
I've given @strk and @imincik admin access to this repo.
